version: '3'
services:
  users:
   build:
    context: .
    dockerfile: ./apps/users/Dockerfile
    target: development
   command: yarn start:dev users
   env_file:
     - ./apps/users/.env
   ports:
     - '3001:3001'
   volumes:
     - .:/usr/src/app
  token:
   build:
    context: .
    dockerfile: ./apps/token/Dockerfile
    target: development
   command: yarn start:dev token
   env_file:
     - ./apps/token/.env
   ports:
     - '3002:3002'
   volumes:
     - .:/usr/src/app
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
  redis:
    image: redis:latest
    container_name: redis-cached-token
    # command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    command: redis-server --requirepass $REDIS_PASS
    ports:
      - '6379:6379'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app